// Copyright (C) Australian Semiconductor Technology Company (ASTC). 2022.
// All Rights Reserved.
//
// This is unpublished proprietary source code of the Australian Semiconductor
// Technology Company (ASTC). The copyright notice does not evidence any actual
// or intended publication of such source code.

// Do not edit this file. It is generated from the marvell_88Q5050 model description.

#ifndef VWORKS_MODELS_MARVELL_88Q5050_COMMON_BASE_HPP
#define VWORKS_MODELS_MARVELL_88Q5050_COMMON_BASE_HPP

#include <systemc>
#include <tlm>
#include <vworks/genesis.hpp>
#include <semantic/semantic.hpp>
#include "Ethernet/EthernetFrame.hpp"
#include "Ethernet/EthernetFrame_systemc.h"

namespace vworks {
namespace models {

class marvell_88Q5050_common_base : public sc_core::sc_module
{
public:
    // Ports
    sc_core::sc_vector<sc_core::sc_out<EthernetFrame> > TX;
    sc_core::sc_vector<sc_core::sc_in<EthernetFrame> > RX;
    sc_core::sc_in<unsigned int> MDIO_in;
    sc_core::sc_out<unsigned int> MDIO_out;

    vworks::genesis::reg_block unmapped_reg_block;
    // Registers
    sc_core::sc_vector<vworks::genesis::reg16> PORT0;
    sc_core::sc_vector<vworks::genesis::reg16> PORT1;
    sc_core::sc_vector<vworks::genesis::reg16> PORT2;
    sc_core::sc_vector<vworks::genesis::reg16> PORT3;
    sc_core::sc_vector<vworks::genesis::reg16> PORT4;
    sc_core::sc_vector<vworks::genesis::reg16> PORT5;
    sc_core::sc_vector<vworks::genesis::reg16> PORT6;
    sc_core::sc_vector<vworks::genesis::reg16> PORT7;
    sc_core::sc_vector<vworks::genesis::reg16> PORT8;
    sc_core::sc_vector<vworks::genesis::reg16> SMI;
    sc_core::sc_vector<vworks::genesis::reg16> GLB1;
    sc_core::sc_vector<vworks::genesis::reg16> GLB2;
    sc_core::sc_vector<vworks::genesis::reg16> TCAM;
    sc_core::sc_vector<vworks::genesis::reg8> SWITCH_MAC_WOL_WOF;

    virtual ~marvell_88Q5050_common_base();

protected:
    marvell_88Q5050_common_base(sc_core::sc_module_name name);
    virtual void reset_ports();
    virtual void reset_registers();

    SEM_SOURCE(source);
};

} // models
} // vworks

#endif // VWORKS_MODELS_MARVELL_88Q5050_COMMON_BASE_HPP
