// Copyright (C) Australian Semiconductor Technology Company (ASTC). 2022.
// All Rights Reserved.
//
// This is unpublished proprietary source code of the Australian Semiconductor
// Technology Company (ASTC). The copyright notice does not evidence any actual
// or intended publication of such source code.

// Do not edit this file. It is generated from the marvell_88Q5050 model description.

#include "marvell_88Q5050_base.hpp"

using namespace sc_core;
using namespace sc_dt;
using namespace vworks::genesis;

namespace vworks {
namespace models {

marvell_88Q5050_base::marvell_88Q5050_base(sc_module_name name) :
    marvell_88Q5050_common(name)
{
}

marvell_88Q5050_base::~marvell_88Q5050_base()
{
}

void marvell_88Q5050_base::reset_ports()
{
    marvell_88Q5050_common::reset_ports();
}

void marvell_88Q5050_base::reset_registers()
{
    marvell_88Q5050_common::reset_registers();
}

} // models
} // vworks
