// Copyright (C) Australian Semiconductor Technology Company (ASTC). 2022.
// All Rights Reserved.
//
// This is unpublished proprietary source code of the Australian Semiconductor
// Technology Company (ASTC). The copyright notice does not evidence any actual
// or intended publication of such source code.

// Do not edit this file. It is generated from the marvell_88Q5050 model description.

#ifndef VWORKS_MODELS_MARVELL_88Q5050_BASE_HPP
#define VWORKS_MODELS_MARVELL_88Q5050_BASE_HPP

#include "marvell_88Q5050_common.hpp"
#include "Ethernet/EthernetFrame.hpp"
#include "Ethernet/EthernetFrame_systemc.h"

namespace vworks {
namespace models {

class marvell_88Q5050_base : public marvell_88Q5050_common
{
public:
    virtual ~marvell_88Q5050_base();

protected:
    marvell_88Q5050_base(sc_core::sc_module_name name);
    virtual void reset_ports();
    virtual void reset_registers();
};

} // models
} // vworks

#endif // VWORKS_MODELS_MARVELL_88Q5050_BASE_HPP
