// Copyright (C) Australian Semiconductor Technology Company (ASTC). 2022.
// All Rights Reserved.
//
// This is unpublished proprietary source code of the Australian Semiconductor
// Technology Company (ASTC). The copyright notice does not evidence any actual
// or intended publication of such source code.

// Do not edit this file. It is generated from the marvell_88Q5050 model description.

#include "marvell_88Q5050_common_base.hpp"

using namespace sc_core;
using namespace sc_dt;
using namespace vworks::genesis;

namespace vworks {
namespace models {

marvell_88Q5050_common_base::marvell_88Q5050_common_base(sc_module_name name) :
    sc_module(name),
    TX("TX", 9),
    RX("RX", 9),
    MDIO_in("MDIO_in"),
    MDIO_out("MDIO_out"),
    unmapped_reg_block("unmapped_reg_block", 806, 0x0ULL, tlm::TLM_UNKNOWN_ENDIAN, 0),
    PORT0("PORT0", 32, reg16::creator(unmapped_reg_block, 0x0ULL, 0x0U, 0xFFFFU)),
    PORT1("PORT1", 32, reg16::creator(unmapped_reg_block, 0x40ULL, 0x0U, 0xFFFFU)),
    PORT2("PORT2", 32, reg16::creator(unmapped_reg_block, 0x80ULL, 0x0U, 0xFFFFU)),
    PORT3("PORT3", 32, reg16::creator(unmapped_reg_block, 0xC0ULL, 0x0U, 0xFFFFU)),
    PORT4("PORT4", 32, reg16::creator(unmapped_reg_block, 0x100ULL, 0x0U, 0xFFFFU)),
    PORT5("PORT5", 32, reg16::creator(unmapped_reg_block, 0x140ULL, 0x0U, 0xFFFFU)),
    PORT6("PORT6", 32, reg16::creator(unmapped_reg_block, 0x180ULL, 0x0U, 0xFFFFU)),
    PORT7("PORT7", 32, reg16::creator(unmapped_reg_block, 0x1C0ULL, 0x0U, 0xFFFFU)),
    PORT8("PORT8", 32, reg16::creator(unmapped_reg_block, 0x200ULL, 0x0U, 0xFFFFU)),
    SMI("SMI", 2, reg16::creator(unmapped_reg_block, 0x240ULL, 0x0U, 0xFFFFU)),
    GLB1("GLB1", 32, reg16::creator(unmapped_reg_block, 0x244ULL, 0x0U, 0xFFFFU)),
    GLB2("GLB2", 32, reg16::creator(unmapped_reg_block, 0x284ULL, 0x0U, 0xFFFFU)),
    TCAM("TCAM", 32, reg16::creator(unmapped_reg_block, 0x2C4ULL, 0x0U, 0xFFFFU)),
    SWITCH_MAC_WOL_WOF("SWITCH_MAC_WOL_WOF", 34, reg8::creator(unmapped_reg_block, 0x304ULL, 0x0U, 0xFFU)),
    source(this->name())
{
}

marvell_88Q5050_common_base::~marvell_88Q5050_common_base()
{
}

void marvell_88Q5050_common_base::reset_ports()
{
}

void marvell_88Q5050_common_base::reset_registers()
{
    unmapped_reg_block.reset();
}

} // models
} // vworks
