#ifndef MARVELL_REGISTERS_HPP
#define MARVELL_REGISTERS_HPP

#define SWITCH_GLB_CTRL GLB1[0x4]
#define SWITCH_MAC_WOL_WOF_REG GLB2[0xD]
#define GLOBAL_CTRL2 GLB1[0x1C]

#define SMI_PHY_CMD_REG GLB2[0x18]
#define SMI_PHY_DATA_REG GLB2[0x19]

#define SMI_CMD_REG SMI[0x0]
#define SMI_DATA_REG SMI[0x1]

#endif